// BIG IF question bank — data-driven registry.
// Add a question = append one row. IDs are STABLE FOREVER (stats + history key
// off them): never renumber, never reuse a deleted id.
// type: "wyr"  = would-you-rather, options a/b
//       "button" = would-you-press-the-button, text = the prize, catch = the cost
//       "hypo" = open-ended hypothetical, no vote, just ponder/share
// cat: silly | gross | money | deep | powers | food | spicy

const QUESTIONS = [
  // ---- would you rather: silly ----
  { id: "wyr-001", type: "wyr", cat: "silly", text: "Would you rather…", a: "fight one horse-sized duck", b: "fight 100 duck-sized horses" },
  { id: "wyr-002", type: "wyr", cat: "silly", text: "Would you rather…", a: "have fingers as long as your legs", b: "have legs as short as your fingers" },
  { id: "wyr-003", type: "wyr", cat: "silly", text: "Would you rather…", a: "honk like a goose every time you laugh", b: "cry glitter" },
  { id: "wyr-004", type: "wyr", cat: "silly", text: "Would you rather…", a: "always speak in rhyme", b: "always sing instead of speak" },
  { id: "wyr-005", type: "wyr", cat: "silly", text: "Would you rather…", a: "have a pet dinosaur the size of a cat", b: "have a pet cat the size of a dinosaur" },
  { id: "wyr-006", type: "wyr", cat: "silly", text: "Would you rather…", a: "sneeze confetti", b: "burp bubbles" },
  { id: "wyr-007", type: "wyr", cat: "silly", text: "Would you rather…", a: "wear clown shoes every day for a year", b: "wear a clown nose every day for a year" },
  { id: "wyr-008", type: "wyr", cat: "silly", text: "Would you rather…", a: "only be able to whisper", b: "only be able to shout" },
  { id: "wyr-009", type: "wyr", cat: "silly", text: "Would you rather…", a: "have a theme song that plays when you enter a room", b: "have a laugh track that plays when you make a joke" },
  { id: "wyr-010", type: "wyr", cat: "silly", text: "Would you rather…", a: "slide everywhere on your knees", b: "cartwheel everywhere" },
  { id: "wyr-011", type: "wyr", cat: "silly", text: "Would you rather…", a: "have hiccups for a year", b: "feel like you need to sneeze but can't for a year" },
  { id: "wyr-012", type: "wyr", cat: "silly", text: "Would you rather…", a: "be chased by one angry swan forever", b: "be silently judged by 50 owls forever" },
  { id: "wyr-013", type: "wyr", cat: "silly", text: "Would you rather…", a: "have hair that changes colour with your mood", b: "have a tail that wags when you're happy" },
  { id: "wyr-014", type: "wyr", cat: "silly", text: "Would you rather…", a: "talk like a pirate forever", b: "walk like a crab forever" },
  { id: "wyr-015", type: "wyr", cat: "silly", text: "Would you rather…", a: "everything you draw becomes real but badly drawn", b: "everything you write comes true but with one typo" },
  { id: "wyr-016", type: "wyr", cat: "silly", text: "Would you rather…", a: "have a belly button that plays music when pressed", b: "have kneecaps that glow in the dark" },
  { id: "wyr-017", type: "wyr", cat: "silly", text: "Would you rather…", a: "be famous for a viral sneeze", b: "be famous for falling over at a wedding" },
  { id: "wyr-018", type: "wyr", cat: "silly", text: "Would you rather…", a: "your shadow does its own thing", b: "your reflection is always one second behind" },
  { id: "wyr-019", type: "wyr", cat: "silly", text: "Would you rather…", a: "enter every room announcing your full name", b: "leave every room moonwalking" },
  { id: "wyr-020", type: "wyr", cat: "silly", text: "Would you rather…", a: "all your shirts are two sizes too small", b: "all your shoes are two sizes too big" },
  { id: "wyr-021", type: "wyr", cat: "silly", text: "Would you rather…", a: "sweat maple syrup", b: "smell like fresh popcorn when nervous" },
  { id: "wyr-022", type: "wyr", cat: "silly", text: "Would you rather…", a: "a duck follows you around narrating your life", b: "a wise voice narrates your life but only in your head" },
  { id: "wyr-023", type: "wyr", cat: "silly", text: "Would you rather…", a: "high-five everyone you ever meet", b: "bow dramatically to everyone you ever meet" },
  { id: "wyr-024", type: "wyr", cat: "silly", text: "Would you rather…", a: "your phone autocorrects everything to 'banana'", b: "your voice randomly switches to opera mid-sentence" },
  { id: "wyr-025", type: "wyr", cat: "silly", text: "Would you rather…", a: "talk to animals but they're all rude", b: "fly but only two feet off the ground" },
  { id: "wyr-026", type: "wyr", cat: "silly", text: "Would you rather…", a: "hiccup every time someone says your name", b: "get the chills every time someone waves at you" },
  { id: "wyr-027", type: "wyr", cat: "silly", text: "Would you rather…", a: "live in a house shaped like a shoe", b: "live in a house shaped like a giant hat" },
  { id: "wyr-028", type: "wyr", cat: "silly", text: "Would you rather…", a: "have permanent jazz hands", b: "have permanent finger guns" },
  { id: "wyr-029", type: "wyr", cat: "silly", text: "Would you rather…", a: "only watch movies as musicals", b: "only read books written in comic sans" },
  { id: "wyr-030", type: "wyr", cat: "silly", text: "Would you rather…", a: "a snail that grants wishes but sometimes lies", b: "a parrot that tells the future but only in riddles" },
  { id: "wyr-031", type: "wyr", cat: "silly", text: "Would you rather…", a: "be 10% funnier but 50% louder", b: "be 50% funnier but nobody hears your jokes first try" },
  { id: "wyr-032", type: "wyr", cat: "silly", text: "Would you rather…", a: "every door you open creaks dramatically", b: "every chair you sit on squeaks suspiciously" },
  { id: "wyr-033", type: "wyr", cat: "silly", text: "Would you rather…", a: "wake up every day with a different accent", b: "wake up every day with a different haircut" },
  { id: "wyr-034", type: "wyr", cat: "silly", text: "Would you rather…", a: "your sneeze sounds like an air horn", b: "your yawn sounds like a wolf howl" },
  { id: "wyr-035", type: "wyr", cat: "silly", text: "Would you rather…", a: "be a wizard with only kitchen spells", b: "be a superhero whose power only works on Tuesdays" },
  { id: "wyr-036", type: "wyr", cat: "silly", text: "Would you rather…", a: "always have a tiny pebble in your shoe", b: "always have one slightly wet sock" },
  { id: "wyr-037", type: "wyr", cat: "silly", text: "Would you rather…", a: "ride a llama to work every day", b: "ride a giant tortoise to work (it takes 4 hours)" },
  { id: "wyr-038", type: "wyr", cat: "silly", text: "Would you rather…", a: "eyebrows that grow an inch every day", b: "a beard of bees (they're friendly)" },
  { id: "wyr-039", type: "wyr", cat: "silly", text: "Would you rather…", a: "everything you touch turns slightly sticky", b: "everything you touch gets slightly warm" },
  { id: "wyr-040", type: "wyr", cat: "silly", text: "Would you rather…", a: "be reincarnated as a pigeon with your memories", b: "be reincarnated as a house cat with no memories" },
  { id: "wyr-041", type: "wyr", cat: "silly", text: "Would you rather…", a: "do a dramatic gasp before every sentence", b: "wink after every sentence" },
  { id: "wyr-042", type: "wyr", cat: "silly", text: "Would you rather…", a: "your GPS voice is your own voice mocking you", b: "your alarm is your own voice, disappointed in you" },
  { id: "wyr-043", type: "wyr", cat: "silly", text: "Would you rather…", a: "own a trampoline-floor house", b: "own a ball-pit basement" },
  { id: "wyr-044", type: "wyr", cat: "silly", text: "Would you rather…", a: "fight crime with a team of raccoons", b: "commit minor crimes with a team of golden retrievers" },
  { id: "wyr-045", type: "wyr", cat: "silly", text: "Would you rather…", a: "have spaghetti hair that regrows daily", b: "have detachable ears you could leave in meetings" },
  { id: "wyr-046", type: "wyr", cat: "silly", text: "Would you rather…", a: "every song you hear is stuck in your head for 24 hours", b: "never remember any song lyrics ever" },
  { id: "wyr-047", type: "wyr", cat: "silly", text: "Would you rather…", a: "be barefoot forever, never stepping on anything sharp", b: "wear great shoes forever that always feel sandy inside" },
  { id: "wyr-048", type: "wyr", cat: "silly", text: "Would you rather…", a: "a rain cloud that only rains on you when you lie", b: "a nose that glows when someone lies to you" },
  { id: "wyr-049", type: "wyr", cat: "silly", text: "Would you rather…", a: "speak every language with a terrible accent", b: "speak only yours but sound incredibly wise" },
  { id: "wyr-050", type: "wyr", cat: "silly", text: "Would you rather…", a: "be attacked by one goose that knows your schedule", b: "be attacked by five geese at one random moment in life" },
  // ---- would you rather: gross ----
  { id: "wyr-051", type: "wyr", cat: "gross", text: "Would you rather…", a: "step in a puddle wearing socks every morning", b: "grab a wet doorknob every morning" },
  { id: "wyr-052", type: "wyr", cat: "gross", text: "Would you rather…", a: "smell like blue cheese to everyone else", b: "everything you eat tastes 5% like blue cheese" },
  { id: "wyr-053", type: "wyr", cat: "gross", text: "Would you rather…", a: "clean a public toilet with a toothbrush", b: "clean your toilet with a stranger's toothbrush, then they use it" },
  { id: "wyr-054", type: "wyr", cat: "gross", text: "Would you rather…", a: "have permanently sweaty hands", b: "have permanently sweaty feet" },
  { id: "wyr-055", type: "wyr", cat: "gross", text: "Would you rather…", a: "find a hair in every meal", b: "find out later there was a bug in one meal a week" },
  { id: "wyr-056", type: "wyr", cat: "gross", text: "Would you rather…", a: "sneeze into your hands forever (no tissues allowed)", b: "sneeze fully open-mouthed forever (no covering)" },
  { id: "wyr-057", type: "wyr", cat: "gross", text: "Would you rather…", a: "wear the same socks for a month", b: "share a toothbrush with your best friend for a month" },
  { id: "wyr-058", type: "wyr", cat: "gross", text: "Would you rather…", a: "swim one lap in a pool of mayonnaise", b: "swim ten laps in a pool of expired milk" },
  { id: "wyr-059", type: "wyr", cat: "gross", text: "Would you rather…", a: "burp uncontrollably during every serious moment", b: "have your stomach growl like a bear in every quiet room" },
  { id: "wyr-060", type: "wyr", cat: "gross", text: "Would you rather…", a: "lick the floor of a bus", b: "lick the handrail of an escalator" },
  { id: "wyr-061", type: "wyr", cat: "gross", text: "Would you rather…", a: "have breath that smells like garbage for a year", b: "have feet that smell like garbage forever" },
  { id: "wyr-062", type: "wyr", cat: "gross", text: "Would you rather…", a: "eat a spoonful of wasabi every morning", b: "eat a raw onion like an apple every week" },
  { id: "wyr-063", type: "wyr", cat: "gross", text: "Would you rather…", a: "your shower drains into your kitchen sink", b: "your kitchen sink drains into your bathtub" },
  { id: "wyr-064", type: "wyr", cat: "gross", text: "Would you rather…", a: "touch every trash can you walk past", b: "smell every stranger's shoe you walk past" },
  { id: "wyr-065", type: "wyr", cat: "gross", text: "Would you rather…", a: "have earwax that smells like vanilla (people notice)", b: "have normal earwax but way too much of it" },
  { id: "wyr-066", type: "wyr", cat: "gross", text: "Would you rather…", a: "eat one bite of dog food daily", b: "eat one full can of dog food once a year" },
  { id: "wyr-067", type: "wyr", cat: "gross", text: "Would you rather…", a: "never be able to wash your hands again", b: "never be able to wash your hair again" },
  { id: "wyr-068", type: "wyr", cat: "gross", text: "Would you rather…", a: "sleep in a bed with sand in it forever", b: "sleep in a bed that's always slightly damp" },
  { id: "wyr-069", type: "wyr", cat: "gross", text: "Would you rather…", a: "hold a tarantula for one minute", b: "have a cockroach walk across your face once" },
  { id: "wyr-070", type: "wyr", cat: "gross", text: "Would you rather…", a: "drink a smoothie made from last night's dinner", b: "eat a soup made from this morning's breakfast, blended" },
  // ---- would you rather: food ----
  { id: "wyr-071", type: "wyr", cat: "food", text: "Would you rather…", a: "never eat pizza again", b: "never eat chocolate again" },
  { id: "wyr-072", type: "wyr", cat: "food", text: "Would you rather…", a: "everything you eat is slightly too salty", b: "everything you eat is slightly too sweet" },
  { id: "wyr-073", type: "wyr", cat: "food", text: "Would you rather…", a: "only eat breakfast foods forever", b: "never eat breakfast foods again" },
  { id: "wyr-074", type: "wyr", cat: "food", text: "Would you rather…", a: "have unlimited free takeaway but it's always lukewarm", b: "cook every meal yourself but it's always perfect" },
  { id: "wyr-075", type: "wyr", cat: "food", text: "Would you rather…", a: "give up cheese forever", b: "give up all sauces forever (yes, all of them)" },
  { id: "wyr-076", type: "wyr", cat: "food", text: "Would you rather…", a: "eat only spicy food forever", b: "eat only bland food forever" },
  { id: "wyr-077", type: "wyr", cat: "food", text: "Would you rather…", a: "drink everything through a tiny coffee stirrer", b: "eat everything with a single chopstick" },
  { id: "wyr-078", type: "wyr", cat: "food", text: "Would you rather…", a: "pineapple on every pizza you ever eat", b: "no toppings on any pizza you ever eat" },
  { id: "wyr-079", type: "wyr", cat: "food", text: "Would you rather…", a: "eat your favourite meal every day forever (only that)", b: "never eat your favourite meal again but eat anything else" },
  { id: "wyr-080", type: "wyr", cat: "food", text: "Would you rather…", a: "all your drinks are room temperature forever", b: "all your food is fridge-cold forever" },
  { id: "wyr-081", type: "wyr", cat: "food", text: "Would you rather…", a: "cereal with water", b: "toast with no butter, forever, as your only breakfast" },
  { id: "wyr-082", type: "wyr", cat: "food", text: "Would you rather…", a: "only be able to eat with your hands", b: "only be able to eat wearing oven mitts (cutlery allowed)" },
  { id: "wyr-083", type: "wyr", cat: "food", text: "Would you rather…", a: "ketchup on everything you eat", b: "mayo on everything you eat" },
  { id: "wyr-084", type: "wyr", cat: "food", text: "Would you rather…", a: "never taste sweetness again", b: "never taste savoury again" },
  { id: "wyr-085", type: "wyr", cat: "food", text: "Would you rather…", a: "your coffee/tea is always 20% too weak", b: "your coffee/tea is always slightly burnt" },
  { id: "wyr-086", type: "wyr", cat: "food", text: "Would you rather…", a: "eat a whole lemon, peel and all, once a month", b: "eat a raw potato once a year" },
  { id: "wyr-087", type: "wyr", cat: "food", text: "Would you rather…", a: "free groceries forever but the brands are random", b: "half-price groceries forever and you choose" },
  { id: "wyr-088", type: "wyr", cat: "food", text: "Would you rather…", a: "every sandwich you make falls apart while eating", b: "every soup you eat is 30% too hot the whole time" },
  { id: "wyr-089", type: "wyr", cat: "food", text: "Would you rather…", a: "eat dessert before every meal (mandatory)", b: "never eat dessert again" },
  { id: "wyr-090", type: "wyr", cat: "food", text: "Would you rather…", a: "only drink water forever", b: "drink anything but water is banned (hydration via food)" },
  // ---- would you rather: money ----
  { id: "wyr-091", type: "wyr", cat: "money", text: "Would you rather…", a: "get $1 million now", b: "get $5,000 a month for life" },
  { id: "wyr-092", type: "wyr", cat: "money", text: "Would you rather…", a: "be rich but everyone assumes you cheated", b: "be broke but everyone thinks you're brilliant" },
  { id: "wyr-093", type: "wyr", cat: "money", text: "Would you rather…", a: "find $100 every time you do laundry", b: "never pay for fuel or public transport again" },
  { id: "wyr-094", type: "wyr", cat: "money", text: "Would you rather…", a: "double your salary but work every weekend", b: "keep your salary and work 4 days a week" },
  { id: "wyr-095", type: "wyr", cat: "money", text: "Would you rather…", a: "a house that's paid off but you can never move", b: "rent forever but live anywhere you want" },
  { id: "wyr-096", type: "wyr", cat: "money", text: "Would you rather…", a: "win the lottery but can't tell anyone ever", b: "earn the same over 20 years and everyone knows" },
  { id: "wyr-097", type: "wyr", cat: "money", text: "Would you rather…", a: "everything you buy is 50% off but secondhand", b: "everything is full price but always brand new" },
  { id: "wyr-098", type: "wyr", cat: "money", text: "Would you rather…", a: "get $10 for every hour you're awake", b: "get $50 for every hour you sleep" },
  { id: "wyr-099", type: "wyr", cat: "money", text: "Would you rather…", a: "your dream job at half your current pay", b: "a boring job at triple your current pay" },
  { id: "wyr-100", type: "wyr", cat: "money", text: "Would you rather…", a: "$100k now, tax-free, no strings", b: "a 10% chance at $10 million (one shot)" },
  { id: "wyr-101", type: "wyr", cat: "money", text: "Would you rather…", a: "never pay for flights again", b: "never pay for hotels again" },
  { id: "wyr-102", type: "wyr", cat: "money", text: "Would you rather…", a: "all your subscriptions are free forever", b: "all your utility bills are free forever" },
  { id: "wyr-103", type: "wyr", cat: "money", text: "Would you rather…", a: "retire at 40 with a modest life", b: "retire at 65 rich" },
  { id: "wyr-104", type: "wyr", cat: "money", text: "Would you rather…", a: "be given a small successful business you must run", b: "be given the same value in cash" },
  { id: "wyr-105", type: "wyr", cat: "money", text: "Would you rather…", a: "everyone can see your bank balance", b: "everyone can see your search history" },
  { id: "wyr-106", type: "wyr", cat: "money", text: "Would you rather…", a: "a card that pays for anything under $10", b: "a card that pays 25% of anything, any price" },
  { id: "wyr-107", type: "wyr", cat: "money", text: "Would you rather…", a: "earn $1 every time someone says your name", b: "earn $100 every time you genuinely laugh" },
  { id: "wyr-108", type: "wyr", cat: "money", text: "Would you rather…", a: "free electricity for life", b: "free internet for life" },
  { id: "wyr-109", type: "wyr", cat: "money", text: "Would you rather…", a: "$1,000 today", b: "$2,000 in exactly one year, guaranteed" },
  { id: "wyr-110", type: "wyr", cat: "money", text: "Would you rather…", a: "be the richest person in a small town", b: "be comfortably average in your dream city" },
  // ---- would you rather: powers ----
  { id: "wyr-111", type: "wyr", cat: "powers", text: "Would you rather…", a: "be able to fly", b: "be able to turn invisible" },
  { id: "wyr-112", type: "wyr", cat: "powers", text: "Would you rather…", a: "read minds but can't turn it off", b: "see 10 minutes into the future but only your own" },
  { id: "wyr-113", type: "wyr", cat: "powers", text: "Would you rather…", a: "teleport anywhere but arrive naked", b: "fly anywhere but at walking speed" },
  { id: "wyr-114", type: "wyr", cat: "powers", text: "Would you rather…", a: "talk to animals", b: "speak every human language" },
  { id: "wyr-115", type: "wyr", cat: "powers", text: "Would you rather…", a: "pause time for everyone but you", b: "rewind your own day once per week" },
  { id: "wyr-116", type: "wyr", cat: "powers", text: "Would you rather…", a: "super strength you can never show anyone", b: "mild telekinesis you can use freely (2kg max)" },
  { id: "wyr-117", type: "wyr", cat: "powers", text: "Would you rather…", a: "heal any injury by touch but feel the pain briefly", b: "never get sick or injured yourself" },
  { id: "wyr-118", type: "wyr", cat: "powers", text: "Would you rather…", a: "control fire", b: "control water" },
  { id: "wyr-119", type: "wyr", cat: "powers", text: "Would you rather…", a: "perfect memory of everything you've ever seen", b: "the ability to forget anything you choose" },
  { id: "wyr-120", type: "wyr", cat: "powers", text: "Would you rather…", a: "be immortal but age normally", b: "live to exactly 90, healthy the whole way" },
  { id: "wyr-121", type: "wyr", cat: "powers", text: "Would you rather…", a: "shape-shift into any animal for 1 hour a day", b: "become any other person for 10 minutes a day" },
  { id: "wyr-122", type: "wyr", cat: "powers", text: "Would you rather…", a: "never need sleep", b: "never need to eat (you still can for fun)" },
  { id: "wyr-123", type: "wyr", cat: "powers", text: "Would you rather…", a: "breathe underwater", b: "survive any fall" },
  { id: "wyr-124", type: "wyr", cat: "powers", text: "Would you rather…", a: "know the answer to any one question, once", b: "get three small wishes with no world-changing power" },
  { id: "wyr-125", type: "wyr", cat: "powers", text: "Would you rather…", a: "make anyone tell the truth for 1 minute a day", b: "become undetectable to cameras whenever you want" },
  { id: "wyr-126", type: "wyr", cat: "powers", text: "Would you rather…", a: "run at 100 km/h", b: "jump 10 metres high" },
  { id: "wyr-127", type: "wyr", cat: "powers", text: "Would you rather…", a: "instantly master any skill but forget it after a week", b: "learn everything at half speed but keep it forever" },
  { id: "wyr-128", type: "wyr", cat: "powers", text: "Would you rather…", a: "see in the dark perfectly", b: "hear conversations up to 100 m away (at will)" },
  { id: "wyr-129", type: "wyr", cat: "powers", text: "Would you rather…", a: "your dreams are shared movies anyone can watch", b: "you can enter other people's dreams (with permission)" },
  { id: "wyr-130", type: "wyr", cat: "powers", text: "Would you rather…", a: "a rewind button for conversations (30 seconds)", b: "a mute button that works on any one person per day" },
  { id: "wyr-131", type: "wyr", cat: "powers", text: "Would you rather…", a: "summon any object under $20 out of thin air", b: "duplicate any object you already own, once each" },
  { id: "wyr-132", type: "wyr", cat: "powers", text: "Would you rather…", a: "be fluent in music (any instrument, instantly)", b: "be fluent in code (any language, instantly)" },
  { id: "wyr-133", type: "wyr", cat: "powers", text: "Would you rather…", a: "control your dreams every night", b: "need only 2 hours of sleep" },
  { id: "wyr-134", type: "wyr", cat: "powers", text: "Would you rather…", a: "talk to plants (they're chatty)", b: "talk to insects (they're surprisingly wise)" },
  { id: "wyr-135", type: "wyr", cat: "powers", text: "Would you rather…", a: "x-ray vision that only works on cardboard boxes", b: "flight that only works during light drizzle" },
  // ---- would you rather: deep ----
  { id: "wyr-136", type: "wyr", cat: "deep", text: "Would you rather…", a: "know how you die", b: "know when you die" },
  { id: "wyr-137", type: "wyr", cat: "deep", text: "Would you rather…", a: "be loved by everyone but respected by no one", b: "be respected by everyone but loved by no one" },
  { id: "wyr-138", type: "wyr", cat: "deep", text: "Would you rather…", a: "relive your best day on loop for a year", b: "skip your worst future year entirely" },
  { id: "wyr-139", type: "wyr", cat: "deep", text: "Would you rather…", a: "know every secret kept from you", b: "have everyone forget your most embarrassing moment" },
  { id: "wyr-140", type: "wyr", cat: "deep", text: "Would you rather…", a: "be the smartest person alive but always doubted", b: "be average but always believed" },
  { id: "wyr-141", type: "wyr", cat: "deep", text: "Would you rather…", a: "live one 1,000-year life", b: "live ten 100-year lives with no memory between" },
  { id: "wyr-142", type: "wyr", cat: "deep", text: "Would you rather…", a: "your life is a book everyone can read after you die", b: "your life vanishes from all records when you die" },
  { id: "wyr-143", type: "wyr", cat: "deep", text: "Would you rather…", a: "always know the truth even when it hurts", b: "stay happily unaware when the truth would crush you" },
  { id: "wyr-144", type: "wyr", cat: "deep", text: "Would you rather…", a: "be famous after your death", b: "be moderately appreciated while alive" },
  { id: "wyr-145", type: "wyr", cat: "deep", text: "Would you rather…", a: "restart life at 5 with everything you know now", b: "jump to 60 with enough money to be comfortable" },
  { id: "wyr-146", type: "wyr", cat: "deep", text: "Would you rather…", a: "your thoughts appear as subtitles above your head", b: "hear everyone's honest first impression of you, once" },
  { id: "wyr-147", type: "wyr", cat: "deep", text: "Would you rather…", a: "never be able to lie", b: "never be lied to (you always know)" },
  { id: "wyr-148", type: "wyr", cat: "deep", text: "Would you rather…", a: "achieve your biggest dream but no one ever knows", b: "be celebrated for something you never actually did" },
  { id: "wyr-149", type: "wyr", cat: "deep", text: "Would you rather…", a: "lose all your memories every 10 years", b: "remember everything, including what you'd rather forget" },
  { id: "wyr-150", type: "wyr", cat: "deep", text: "Would you rather…", a: "a guaranteed ordinary life", b: "a coin flip between extraordinary and terrible" },
  { id: "wyr-151", type: "wyr", cat: "deep", text: "Would you rather…", a: "know the purpose of the universe but can't tell anyone", b: "everyone else finds out but you never do" },
  { id: "wyr-152", type: "wyr", cat: "deep", text: "Would you rather…", a: "your five closest friends pick your career", b: "your parents pick your partner" },
  { id: "wyr-153", type: "wyr", cat: "deep", text: "Would you rather…", a: "feel everything twice as intensely", b: "feel everything at half intensity" },
  { id: "wyr-154", type: "wyr", cat: "deep", text: "Would you rather…", a: "be the last generation on a healthy Earth", b: "be the first generation on a new planet" },
  { id: "wyr-155", type: "wyr", cat: "deep", text: "Would you rather…", a: "everyone remembers you slightly better than you were", b: "everyone remembers you exactly as you were" },
  { id: "wyr-156", type: "wyr", cat: "deep", text: "Would you rather…", a: "get one honest answer from anyone dead", b: "leave one guaranteed-delivered message after you die" },
  { id: "wyr-157", type: "wyr", cat: "deep", text: "Would you rather…", a: "your biggest regret never happened", b: "your best moment lasts twice as long in memory" },
  { id: "wyr-158", type: "wyr", cat: "deep", text: "Would you rather…", a: "be free but always slightly lost", b: "have a clear path you didn't choose" },
  { id: "wyr-159", type: "wyr", cat: "deep", text: "Would you rather…", a: "everyone always tells you the truth about yourself", b: "no one ever criticises you again" },
  { id: "wyr-160", type: "wyr", cat: "deep", text: "Would you rather…", a: "trade one year of life for your dream body", b: "trade one year of life for your dream mind" },
  // ---- would you rather: spicy (awkward / hot takes, PG-13) ----
  { id: "wyr-161", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your browser history is public for a day", b: "your group chats are public for a day" },
  { id: "wyr-162", type: "wyr", cat: "spicy", text: "Would you rather…", a: "accidentally like your ex's photo from 3 years ago", b: "send 'I miss you' to the wrong person" },
  { id: "wyr-163", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your crush reads your diary", b: "your boss reads your diary" },
  { id: "wyr-164", type: "wyr", cat: "spicy", text: "Would you rather…", a: "date someone your friends hate", b: "date someone who hates your friends" },
  { id: "wyr-165", type: "wyr", cat: "spicy", text: "Would you rather…", a: "know exactly what your ex says about you", b: "your ex knows exactly what you say about them" },
  { id: "wyr-166", type: "wyr", cat: "spicy", text: "Would you rather…", a: "get caught singing dramatically in your car", b: "get caught talking to yourself in a mirror" },
  { id: "wyr-167", type: "wyr", cat: "spicy", text: "Would you rather…", a: "call your teacher/boss 'mum'", b: "wave back at someone waving at the person behind you" },
  { id: "wyr-168", type: "wyr", cat: "spicy", text: "Would you rather…", a: "marry someone who's always 20 minutes late", b: "marry someone who's always 40 minutes early and smug about it" },
  { id: "wyr-169", type: "wyr", cat: "spicy", text: "Would you rather…", a: "everyone knows your salary", b: "everyone knows your screen time" },
  { id: "wyr-170", type: "wyr", cat: "spicy", text: "Would you rather…", a: "laugh loudly at a funeral (once, uncontrollably)", b: "cry loudly at a stranger's wedding (once, uncontrollably)" },
  { id: "wyr-171", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your partner rates your cooking honestly", b: "your partner rates your driving honestly" },
  { id: "wyr-172", type: "wyr", cat: "spicy", text: "Would you rather…", a: "re-send every text you've ever regretted", b: "unsend every text but the recipients remember them" },
  { id: "wyr-173", type: "wyr", cat: "spicy", text: "Would you rather…", a: "trip on stage at your own graduation", b: "have your phone go off loudly at a funeral" },
  { id: "wyr-174", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your most-played song of the year is announced at work", b: "your most-watched video genre is announced at dinner" },
  { id: "wyr-175", type: "wyr", cat: "spicy", text: "Would you rather…", a: "always say what you're thinking for one day a month", b: "never be able to compliment anyone again" },
  { id: "wyr-176", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your parents can hear your inner monologue for a day", b: "your coworkers can, for a week" },
  { id: "wyr-177", type: "wyr", cat: "spicy", text: "Would you rather…", a: "be famous for something cringe", b: "be anonymous forever despite doing something great" },
  { id: "wyr-178", type: "wyr", cat: "spicy", text: "Would you rather…", a: "get a tattoo chosen by your best friend (permanent)", b: "get a haircut chosen by your worst enemy (grows back)" },
  { id: "wyr-179", type: "wyr", cat: "spicy", text: "Would you rather…", a: "everyone sees you exactly as you see yourself", b: "you see yourself exactly as everyone sees you" },
  { id: "wyr-180", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your search suggestions shown on a first date", b: "your camera roll shown at a job interview" },
  // ---- would you rather: mixed bonus round ----
  { id: "wyr-181", type: "wyr", cat: "silly", text: "Would you rather…", a: "have a rewind remote for your pet's zoomies", b: "have subtitles for your pet's noises" },
  { id: "wyr-182", type: "wyr", cat: "deep", text: "Would you rather…", a: "visit any moment in history (watch only)", b: "see one year into your own future (watch only)" },
  { id: "wyr-183", type: "wyr", cat: "silly", text: "Would you rather…", a: "it's always 5 degrees too hot", b: "it's always 5 degrees too cold" },
  { id: "wyr-184", type: "wyr", cat: "powers", text: "Would you rather…", a: "a pause button for your hunger", b: "a fast-forward button for queues (you still wait, it feels instant)" },
  { id: "wyr-185", type: "wyr", cat: "silly", text: "Would you rather…", a: "live in a treehouse with great wifi", b: "live in a mansion with terrible wifi" },
  { id: "wyr-186", type: "wyr", cat: "deep", text: "Would you rather…", a: "be 20% happier but never excited", b: "keep your ups and downs exactly as they are" },
  { id: "wyr-187", type: "wyr", cat: "silly", text: "Would you rather…", a: "your handwriting is always perfect but tiny", b: "your handwriting is huge but chaotic" },
  { id: "wyr-188", type: "wyr", cat: "food", text: "Would you rather…", a: "a bottomless snack drawer (random snacks)", b: "one perfect snack, always available, but only that one" },
  { id: "wyr-189", type: "wyr", cat: "money", text: "Would you rather…", a: "everything you sell goes for 20% more", b: "everything you buy costs 10% less" },
  { id: "wyr-190", type: "wyr", cat: "silly", text: "Would you rather…", a: "be a background extra in every movie ever made", b: "be the lead in one movie nobody watches" },
  // ---- would you press the button? text = prize, catch = cost ----
  { id: "btn-001", type: "button", cat: "money", text: "You get $10 million…", catch: "but you can never eat cheese again." },
  { id: "btn-002", type: "button", cat: "money", text: "You get $1 million…", catch: "but you have to start completely over in a new country, alone." },
  { id: "btn-003", type: "button", cat: "powers", text: "You can fly…", catch: "but only while everyone you know is watching." },
  { id: "btn-004", type: "button", cat: "money", text: "You never pay rent or a mortgage again…", catch: "but your home has one permanently sticky floor tile that moves daily." },
  { id: "btn-005", type: "button", cat: "silly", text: "You become best friends with any celebrity…", catch: "but you hiccup loudly every time they speak." },
  { id: "btn-006", type: "button", cat: "deep", text: "You learn the full truth about anything you choose…", catch: "but you can never share it with anyone." },
  { id: "btn-007", type: "button", cat: "money", text: "You get $100,000…", catch: "but a random person you know gets $1 million and finds out you pressed." },
  { id: "btn-008", type: "button", cat: "silly", text: "You can teleport…", catch: "but every arrival is announced by a loud kazoo fanfare." },
  { id: "btn-009", type: "button", cat: "food", text: "Your favourite meal is free forever, anywhere…", catch: "but you can only ever drink water." },
  { id: "btn-010", type: "button", cat: "deep", text: "You get 10 extra healthy years of life…", catch: "but they're added to the middle, and you know exactly when." },
  { id: "btn-011", type: "button", cat: "powers", text: "You can read minds…", catch: "but everyone can tell when you're doing it." },
  { id: "btn-012", type: "button", cat: "money", text: "You win the lottery…", catch: "but your most embarrassing moment becomes a popular meme." },
  { id: "btn-013", type: "button", cat: "silly", text: "You get a lifetime supply of your favourite snack…", catch: "but every bag/box is slightly, visibly, already open." },
  { id: "btn-014", type: "button", cat: "deep", text: "World hunger is solved…", catch: "but no one will ever know it was you, and you lose everything you own." },
  { id: "btn-015", type: "button", cat: "powers", text: "You never feel physical pain again…", catch: "but you also never feel a hug properly again." },
  { id: "btn-016", type: "button", cat: "money", text: "You get $500 every day for life…", catch: "but you must spend it all before midnight or it vanishes and resets to $50." },
  { id: "btn-017", type: "button", cat: "silly", text: "Your pet can talk…", catch: "but it roasts you in front of guests." },
  { id: "btn-018", type: "button", cat: "spicy", text: "You can see who viewed your profile…", catch: "but everyone can see you checked." },
  { id: "btn-019", type: "button", cat: "deep", text: "You get a do-over on any one decision in your life…", catch: "but you don't get to choose which one — your gut picks." },
  { id: "btn-020", type: "button", cat: "food", text: "You cook like a world-class chef…", catch: "but only when no one will taste it." },
  { id: "btn-021", type: "button", cat: "money", text: "All your debts are erased…", catch: "but so is your favourite memory." },
  { id: "btn-022", type: "button", cat: "silly", text: "You always win rock-paper-scissors…", catch: "but you must play it for every decision anyone offers." },
  { id: "btn-023", type: "button", cat: "powers", text: "You can pause time for 10 minutes a day…", catch: "but you age during every pause, double speed." },
  { id: "btn-024", type: "button", cat: "spicy", text: "You find out what everyone honestly thinks of you…", catch: "but they find out you know." },
  { id: "btn-025", type: "button", cat: "money", text: "Free first-class flights for life…", catch: "but every trip, your luggage is lost for exactly 24 hours." },
  { id: "btn-026", type: "button", cat: "silly", text: "You have perfect hair every day…", catch: "but one sock is always inside out and slightly twisted." },
  { id: "btn-027", type: "button", cat: "deep", text: "You become fluent in every language on Earth…", catch: "but you lose the ability to sing, hum, or whistle forever." },
  { id: "btn-028", type: "button", cat: "food", text: "Calories no longer affect you…", catch: "but everything tastes 15% less delicious." },
  { id: "btn-029", type: "button", cat: "powers", text: "You never need to sleep again…", catch: "but you can never dream again either." },
  { id: "btn-030", type: "button", cat: "money", text: "You get $50,000 right now…", catch: "but you can't use the internet for a year." },
  { id: "btn-031", type: "button", cat: "silly", text: "Traffic lights are always green for you…", catch: "but every song on the radio is 4% too slow." },
  { id: "btn-032", type: "button", cat: "spicy", text: "Your future wedding is fully paid for…", catch: "but your ex plans the whole thing." },
  { id: "btn-033", type: "button", cat: "deep", text: "You get to meet your hero…", catch: "but they will be having their worst day ever." },
  { id: "btn-034", type: "button", cat: "powers", text: "You can breathe underwater…", catch: "but you can now only sleep underwater too." },
  { id: "btn-035", type: "button", cat: "money", text: "Your salary triples…", catch: "but your commute becomes 2 hours each way, no remote work." },
  { id: "btn-036", type: "button", cat: "silly", text: "You get a jetpack…", catch: "but it only works when you're late." },
  { id: "btn-037", type: "button", cat: "food", text: "Unlimited free coffee/tea forever…", catch: "but it's always served in a slightly dirty-looking mug (it's clean, it just looks off)." },
  { id: "btn-038", type: "button", cat: "deep", text: "Everyone in the world becomes 10% kinder…", catch: "but no one remembers your name, ever, on first meeting." },
  { id: "btn-039", type: "button", cat: "spicy", text: "You can undo one sent message per week…", catch: "but one random old message gets re-sent per month." },
  { id: "btn-040", type: "button", cat: "powers", text: "You gain a photographic memory…", catch: "but you can no longer skim anything — you read every word." },
  { id: "btn-041", type: "button", cat: "money", text: "You inherit a beautiful castle…", catch: "but it's haunted by a ghost who critiques your outfits." },
  { id: "btn-042", type: "button", cat: "silly", text: "Your phone battery never dies…", catch: "but your ringtone is stuck on a rooster crow at max volume." },
  { id: "btn-043", type: "button", cat: "deep", text: "You get one guaranteed 'yes' from anyone…", catch: "but you must use it within 24 hours of pressing." },
  { id: "btn-044", type: "button", cat: "food", text: "Pizza is now a health food (for you only)…", catch: "but salad is now junk food (for you only)." },
  { id: "btn-045", type: "button", cat: "powers", text: "You can talk to animals…", catch: "but they never stop talking to you. Ever." },
  { id: "btn-046", type: "button", cat: "money", text: "You get $1,000 every time it rains…", catch: "but you must stand outside in it for at least a minute." },
  { id: "btn-047", type: "button", cat: "silly", text: "You become incredibly photogenic…", catch: "but only in photos you don't know are being taken." },
  { id: "btn-048", type: "button", cat: "spicy", text: "You always know when someone is lying…", catch: "but you blurt 'LIE!' involuntarily 10% of the time." },
  { id: "btn-049", type: "button", cat: "deep", text: "Your worst enemy forgives you completely…", catch: "but you must publicly apologise first, sincerely." },
  { id: "btn-050", type: "button", cat: "food", text: "You get a personal chef for life…", catch: "but they hum loudly and off-key while cooking, always." },
  { id: "btn-051", type: "button", cat: "powers", text: "You can turn invisible…", catch: "but only for 10 seconds at a time, with a loud pop at each end." },
  { id: "btn-052", type: "button", cat: "money", text: "Your bank balance gains 10x interest…", catch: "but you can only check it once a year." },
  { id: "btn-053", type: "button", cat: "silly", text: "You win every board game you ever play…", catch: "but you must gloat, extensively, every time. It's compulsory." },
  { id: "btn-054", type: "button", cat: "deep", text: "You add 5 healthy years to a loved one's life…", catch: "but they'll never know, and you can never tell them." },
  { id: "btn-055", type: "button", cat: "spicy", text: "Your most flattering photo becomes your ID forever…", catch: "but your least flattering photo becomes your work badge." },
  { id: "btn-056", type: "button", cat: "food", text: "Every meal you eat is your exact craving…", catch: "but you must eat it with a comically tiny fork." },
  { id: "btn-057", type: "button", cat: "powers", text: "You never lose anything again…", catch: "but you now always know exactly where everything is — including things you'd rather not." },
  { id: "btn-058", type: "button", cat: "money", text: "You get paid your salary to do nothing…", catch: "but you cannot do any other paid or recognised work, ever." },
  { id: "btn-059", type: "button", cat: "silly", text: "Your laugh becomes infectious (literally, everyone joins)…", catch: "but your sneeze makes everyone in the room sneeze too." },
  { id: "btn-060", type: "button", cat: "deep", text: "You erase your single most painful memory…", catch: "but you also lose everything that moment taught you." },
  { id: "btn-061", type: "button", cat: "powers", text: "You get super speed…", catch: "but your shoes wear out daily and you must buy them yourself." },
  { id: "btn-062", type: "button", cat: "money", text: "A mystery benefactor pays all your bills…", catch: "but once a year they ask one favour. It's always weird. Never illegal, just weird." },
  { id: "btn-063", type: "button", cat: "spicy", text: "You can rewatch any memory in perfect detail…", catch: "but a random friend can too, once a year, and picks the memory." },
  { id: "btn-064", type: "button", cat: "silly", text: "Your car/bike never breaks down…", catch: "but it plays circus music, quietly but audibly, when you park." },
  { id: "btn-065", type: "button", cat: "food", text: "Ice cream no longer melts around you…", catch: "but soup is now always slightly too cold for you." },
  { id: "btn-066", type: "button", cat: "deep", text: "You become the best in the world at the thing you love…", catch: "but you'll never enjoy it quite as much again." },
  { id: "btn-067", type: "button", cat: "powers", text: "You gain perfect intuition about people…", catch: "but you lose the ability to be pleasantly surprised by them." },
  { id: "btn-068", type: "button", cat: "money", text: "Everything you own doubles in value…", catch: "but you can never sell your favourite possession." },
  { id: "btn-069", type: "button", cat: "silly", text: "You get a real lightsaber…", catch: "but it's pool-noodle soft and makes the sounds anyway." },
  { id: "btn-070", type: "button", cat: "spicy", text: "Your crush texts you first, always…", catch: "but your mum is somehow cc'd on every conversation." },
  { id: "btn-071", type: "button", cat: "deep", text: "You get to ask the universe one question…", catch: "but the answer will be honest, complete, and possibly devastating." },
  { id: "btn-072", type: "button", cat: "food", text: "Your fridge restocks itself magically…", catch: "but it judges you — audibly sighing when you open it after 10pm." },
  { id: "btn-073", type: "button", cat: "powers", text: "You can heal any headache, ache, or cold instantly…", catch: "but only other people's, never your own." },
  { id: "btn-074", type: "button", cat: "money", text: "You find $20 in every jacket pocket, always…", catch: "but you lose your keys twice as often." },
  { id: "btn-075", type: "button", cat: "silly", text: "You become fluent in whale song…", catch: "and yes, there is a whale who wants to talk to you. Constantly. About drama." },
  { id: "btn-076", type: "button", cat: "deep", text: "Everyone who ever doubted you sees your success…", catch: "but so does everyone you ever let down." },
  { id: "btn-077", type: "button", cat: "spicy", text: "You get invited to every party…", catch: "but you must arrive first and leave last at each one you attend." },
  { id: "btn-078", type: "button", cat: "food", text: "You can taste-test anything before ordering…", catch: "but the waiter announces your final choice to the whole restaurant." },
  { id: "btn-079", type: "button", cat: "powers", text: "Your plants, pets, and devices never die/break…", catch: "but they all develop mild, persistent opinions." },
  { id: "btn-080", type: "button", cat: "money", text: "You get a private island…", catch: "but the wifi only works at one mysterious spot that moves daily." },
  { id: "btn-081", type: "button", cat: "silly", text: "You can high-five through phone screens…", catch: "but every handshake now honks like a bike horn." },
  { id: "btn-082", type: "button", cat: "deep", text: "You instantly finish every project you've started…", catch: "but you can never start a new one without finishing it." },
  { id: "btn-083", type: "button", cat: "spicy", text: "You see your compatibility score with everyone…", catch: "but it hovers visibly over YOUR head for others too." },
  { id: "btn-084", type: "button", cat: "food", text: "Every birthday cake you get is your dream cake…", catch: "but you must sing the last verse of Happy Birthday alone, as a solo, every time." },
  { id: "btn-085", type: "button", cat: "powers", text: "You remember every dream perfectly…", catch: "but so does one random person you know, about your dreams." },
  { id: "btn-086", type: "button", cat: "money", text: "Your rent/mortgage is frozen forever at today's price…", catch: "but your neighbours are a 24/7 amateur drum circle (they're getting better, slowly)." },
  { id: "btn-087", type: "button", cat: "silly", text: "You get an actual working hoverboard…", catch: "but it only hovers 2 cm and screams when turning." },
  { id: "btn-088", type: "button", cat: "deep", text: "The next generation inherits a fixed climate…", catch: "but no one alive today gets any credit or thanks for it." },
  { id: "btn-089", type: "button", cat: "spicy", text: "You always have the perfect comeback…", catch: "but only 10 seconds after the moment has passed. It's compulsory to say it anyway." },
  { id: "btn-090", type: "button", cat: "food", text: "You never burn your mouth on hot food again…", catch: "but every drink you're handed is 80% ice." },
  { id: "btn-091", type: "button", cat: "powers", text: "You can skip any queue, once per day…", catch: "but everyone in the queue knows, and remembers your face." },
  { id: "btn-092", type: "button", cat: "money", text: "You get $5 million…", catch: "but you must live with no phone or computer for 3 full years first." },
  { id: "btn-093", type: "button", cat: "silly", text: "Your shower is always the perfect temperature…", catch: "but the water pressure is tied to your singing volume." },
  { id: "btn-094", type: "button", cat: "deep", text: "You find your true calling, guaranteed…", catch: "but it pays terribly and your family thinks it's a phase." },
  { id: "btn-095", type: "button", cat: "spicy", text: "Everyone finds you 20% more attractive…", catch: "but photos of you are 20% worse." },
  { id: "btn-096", type: "button", cat: "food", text: "Free dessert at every restaurant, forever…", catch: "but the waiter always says 'someone's got a sweet tooth!' loudly." },
  { id: "btn-097", type: "button", cat: "powers", text: "You get one real magic spell of your design…", catch: "but a random stranger somewhere gets the exact same spell." },
  { id: "btn-098", type: "button", cat: "money", text: "You get a lifetime of free electronics…", catch: "but always the model one generation behind." },
  { id: "btn-099", type: "button", cat: "silly", text: "Your umbrella never breaks or flips…", catch: "but it's aggressively floral no matter what you buy." },
  { id: "btn-100", type: "button", cat: "deep", text: "You get complete inner peace…", catch: "but you lose all your ambition with it." },
  { id: "btn-101", type: "button", cat: "spicy", text: "You can mute anyone in real life for an hour daily…", catch: "but they receive a notification: muted by you." },
  { id: "btn-102", type: "button", cat: "food", text: "Every fruit you buy is perfectly ripe…", catch: "but every avocado in your house judges your timing anyway and browns out of spite." },
  { id: "btn-103", type: "button", cat: "powers", text: "You can fast-forward boring meetings (for you)…", catch: "but afterwards you must accurately summarise what you skipped." },
  { id: "btn-104", type: "button", cat: "money", text: "Your car parks itself perfectly, always…", catch: "but exclusively in the spot furthest from the entrance." },
  { id: "btn-105", type: "button", cat: "silly", text: "You get a genuine suit of medieval armour that fits…", catch: "but you must wear it to one important event per year. You don't pick which." },
  { id: "btn-106", type: "button", cat: "deep", text: "Your kindest act ever goes viral…", catch: "and so does the pettiest thing you've ever done, same day." },
  { id: "btn-107", type: "button", cat: "spicy", text: "You can read your pet's mind for one day…", catch: "but your pet gets to read yours for a week and WILL act differently after." },
  { id: "btn-108", type: "button", cat: "food", text: "Your packed lunch is always exactly what you fancy…", catch: "but a colleague always says 'ooh what's THAT' and requires a full explanation." },
  { id: "btn-109", type: "button", cat: "powers", text: "You gain the power to perfectly parallel park, first try, forever…", catch: "but only while a crowd is watching. Alone, you take 9 attempts." },
  { id: "btn-110", type: "button", cat: "money", text: "You get $250,000 today…", catch: "but you age one extra year, right now, tonight." },
  // ---- open-ended hypotheticals: no vote, just ponder + share ----
  { id: "hyp-001", type: "hypo", cat: "deep", text: "If you could relive one ordinary day from your past — not a big event, just a normal day — which would you pick?" },
  { id: "hyp-002", type: "hypo", cat: "silly", text: "You wake up as the last person on Earth, but everything still works. What's the first thing you do?" },
  { id: "hyp-003", type: "hypo", cat: "money", text: "You must spend $1 million in 24 hours. Nothing can be saved, invested, or given away. What do you buy?" },
  { id: "hyp-004", type: "hypo", cat: "powers", text: "You can make one everyday annoyance illegal, enforced worldwide. What's banned?" },
  { id: "hyp-005", type: "hypo", cat: "deep", text: "If you could send one sentence back to yourself 10 years ago, what would it say?" },
  { id: "hyp-006", type: "hypo", cat: "silly", text: "You're now the villain in a movie. What's your extremely petty evil scheme?" },
  { id: "hyp-007", type: "hypo", cat: "food", text: "You can make one food calorie-free forever, for everyone. Which food gets the honour?" },
  { id: "hyp-008", type: "hypo", cat: "deep", text: "An alien asks you to explain what humans are like in exactly three words. Go." },
  { id: "hyp-009", type: "hypo", cat: "spicy", text: "You can anonymously plant one thought in everyone's head at 9am tomorrow. What is it?" },
  { id: "hyp-010", type: "hypo", cat: "silly", text: "Animals can now vote in elections. Which animal's political opinions worry you most?" },
  { id: "hyp-011", type: "hypo", cat: "powers", text: "You get one superpower, but it must be completely useless in emergencies. What do you pick?" },
  { id: "hyp-012", type: "hypo", cat: "deep", text: "If your life so far had chapter titles, what would the current chapter be called?" },
  { id: "hyp-013", type: "hypo", cat: "money", text: "A stranger hands you $10,000 and says 'make the world 1% better with this.' What do you do?" },
  { id: "hyp-014", type: "hypo", cat: "silly", text: "You must replace your hands with any two objects. What do you choose?" },
  { id: "hyp-015", type: "hypo", cat: "food", text: "Design your final meal — no limits, any chef, anywhere. What's on the table?" },
  { id: "hyp-016", type: "hypo", cat: "deep", text: "What's something you believed strongly 5 years ago that you've completely changed your mind on?" },
  { id: "hyp-017", type: "hypo", cat: "spicy", text: "You can see one statistic floating above everyone's head. What do you choose to see?" },
  { id: "hyp-018", type: "hypo", cat: "silly", text: "Gravity turns off for 10 seconds every day at noon. How does society adapt?" },
  { id: "hyp-019", type: "hypo", cat: "powers", text: "You can permanently swap any two words in the English language for everyone. Which two?" },
  { id: "hyp-020", type: "hypo", cat: "deep", text: "If money and judgement didn't exist, what would you actually do all day?" },
  { id: "hyp-021", type: "hypo", cat: "silly", text: "You're given a fully-staffed castle but must defend it from one knight, once a year. What's your strategy?" },
  { id: "hyp-022", type: "hypo", cat: "money", text: "Your exact salary, but the job is chosen by a random wheel of all jobs. Spin or keep?" },
  { id: "hyp-023", type: "hypo", cat: "deep", text: "What's the smallest thing someone did for you that you still remember years later?" },
  { id: "hyp-024", type: "hypo", cat: "spicy", text: "Everyone gets a warning label that's legally required to be accurate. What does yours say?" },
  { id: "hyp-025", type: "hypo", cat: "silly", text: "You can only communicate via one movie's quotes for a week. Which movie survives this best?" },
  { id: "hyp-026", type: "hypo", cat: "food", text: "One condiment is elected world leader. Which one causes the least chaos?" },
  { id: "hyp-027", type: "hypo", cat: "powers", text: "You can un-invent one thing. What disappears from history?" },
  { id: "hyp-028", type: "hypo", cat: "deep", text: "If you had a guaranteed audience of the whole world for 60 seconds, what would you say?" },
  { id: "hyp-029", type: "hypo", cat: "silly", text: "Your ghost can haunt one location forever. Where do you set up shop, and what's your signature move?" },
  { id: "hyp-030", type: "hypo", cat: "money", text: "You must give one person you know $100,000, but never yourself or family. Who gets it and why?" },
  { id: "hyp-031", type: "hypo", cat: "deep", text: "What would 10-year-old you be most impressed by about your life right now?" },
  { id: "hyp-032", type: "hypo", cat: "silly", text: "All doors are now beaded curtains. Which industry collapses first?" },
  { id: "hyp-033", type: "hypo", cat: "spicy", text: "You get a receipt every time someone mentions you in a conversation you're not in. Do you read them?" },
  { id: "hyp-034", type: "hypo", cat: "powers", text: "You can master any skill instantly, but you must give up one you already have. What's the trade?" },
  { id: "hyp-035", type: "hypo", cat: "food", text: "You open a restaurant that serves only one dish. What dish is worth betting your life savings on?" },
  { id: "hyp-036", type: "hypo", cat: "deep", text: "If your pet (or a pet you know) could leave you a one-sentence review, what would it honestly say?" },
  { id: "hyp-037", type: "hypo", cat: "silly", text: "Every lie you tell adds one inch to your height, permanently. How tall are you in a year?" },
  { id: "hyp-038", type: "hypo", cat: "money", text: "You find a briefcase with $50,000 and a note: 'spend it only on experiences.' What's the plan?" },
  { id: "hyp-039", type: "hypo", cat: "deep", text: "Which fictional character's life advice would actually be terrible if you followed it?" },
  { id: "hyp-040", type: "hypo", cat: "spicy", text: "Your phone announces your most-used app to anyone who asks. What's it saying about you?" },
  { id: "hyp-041", type: "hypo", cat: "silly", text: "You're shrunk to 5 cm tall for 24 hours, back to normal after. What's the itinerary?" },
  { id: "hyp-042", type: "hypo", cat: "powers", text: "You can give one superpower to your least tech-savvy relative. What's safest?" },
  { id: "hyp-043", type: "hypo", cat: "deep", text: "What's a compliment you received once and never forgot?" },
  { id: "hyp-044", type: "hypo", cat: "food", text: "You must eat the same breakfast for the rest of your life. What earns the permanent slot?" },
  { id: "hyp-045", type: "hypo", cat: "silly", text: "Pigeons are revealed to be government drones — but for a hobby, which conspiracy would be the most fun to be true?" },
  { id: "hyp-046", type: "hypo", cat: "money", text: "Every purchase over $100 requires you to explain why to a panel of your grandparents. What changes?" },
  { id: "hyp-047", type: "hypo", cat: "deep", text: "If you could permanently delete one worry from your brain, which goes first?" },
  { id: "hyp-048", type: "hypo", cat: "spicy", text: "A documentary is made about your last 12 months. What's it titled, and what's the genre?" },
  { id: "hyp-049", type: "hypo", cat: "silly", text: "You can add one completely new rule to a sport of your choice. What rule, what sport, what chaos?" },
  { id: "hyp-050", type: "hypo", cat: "powers", text: "Time freezes for everyone but you for one hour a day. After a month, what have you actually done with it?" },
  { id: "hyp-051", type: "hypo", cat: "deep", text: "What's something ordinary today that you think will amaze people in 100 years?" },
  { id: "hyp-052", type: "hypo", cat: "food", text: "One snack is declared a controlled substance. Which one would genuinely cause smuggling rings?" },
  { id: "hyp-053", type: "hypo", cat: "silly", text: "Your reflection starts giving you daily feedback. Is it kind, brutal, or weirdly obsessed with your posture?" },
  { id: "hyp-054", type: "hypo", cat: "money", text: "You get free rent forever in any building that isn't a home (museum, stadium, library…). Where do you live?" },
  { id: "hyp-055", type: "hypo", cat: "deep", text: "Who is someone you've never thanked properly, and what for?" },
  { id: "hyp-056", type: "hypo", cat: "spicy", text: "Everyone's age is replaced by their maturity level, publicly visible. Are you older or younger?" },
  { id: "hyp-057", type: "hypo", cat: "silly", text: "You must add one mythical creature to the real world. Which causes the best chaos-to-danger ratio?" },
  { id: "hyp-058", type: "hypo", cat: "powers", text: "You can make one law of physics take a day off, once a year. Which one, and what's the plan?" },
  { id: "hyp-059", type: "hypo", cat: "deep", text: "If your future self showed up right now and just shook their head slowly, what would you assume it's about?" },
  { id: "hyp-060", type: "hypo", cat: "silly", text: "The moon is now a giant disco ball on weekends. How does Saturday night change on Earth?" },
  // ---- would you rather: round two ----
  { id: "wyr-191", type: "wyr", cat: "gross", text: "Would you rather…", a: "hiccup and burp at the same time, every time", b: "sneeze exactly seven times in a row, every time" },
  { id: "wyr-192", type: "wyr", cat: "silly", text: "Would you rather…", a: "your knees bend both ways", b: "your elbows are always slightly damp" },
  { id: "wyr-193", type: "wyr", cat: "deep", text: "Would you rather…", a: "read a full transcript of everything you said last year", b: "watch a supercut of your facial expressions from last year" },
  { id: "wyr-194", type: "wyr", cat: "food", text: "Would you rather…", a: "every meal comes with unlimited perfect chips/fries", b: "every meal comes with unlimited perfect garlic bread" },
  { id: "wyr-195", type: "wyr", cat: "money", text: "Would you rather…", a: "get paid double to do your job blindfolded one day a week", b: "get paid normally but never attend another meeting" },
  { id: "wyr-196", type: "wyr", cat: "powers", text: "Would you rather…", a: "your whistle summons a friendly crow", b: "your snap summons a suspicious but loyal seagull" },
  { id: "wyr-197", type: "wyr", cat: "silly", text: "Would you rather…", a: "always know exactly what time it is, to the second", b: "always know exactly where north is, smugly" },
  { id: "wyr-198", type: "wyr", cat: "deep", text: "Would you rather…", a: "everyone you meet remembers your name forever", b: "you remember everyone's name forever" },
  { id: "wyr-199", type: "wyr", cat: "gross", text: "Would you rather…", a: "your towels are never quite dry", b: "your bedsheets always have a few crumbs" },
  { id: "wyr-200", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your first date sees your unfiltered camera roll", b: "your first date talks to your most honest friend for 10 minutes" },
  { id: "wyr-201", type: "wyr", cat: "silly", text: "Would you rather…", a: "own a dog that can skateboard but insists on it everywhere", b: "own a cat that can talk but only complains" },
  { id: "wyr-202", type: "wyr", cat: "food", text: "Would you rather…", a: "your tap dispenses sparkling water", b: "your tap dispenses perfectly cold still water (never lukewarm)" },
  { id: "wyr-203", type: "wyr", cat: "money", text: "Would you rather…", a: "a $200 gift card every week to a random shop", b: "$100 cash every week" },
  { id: "wyr-204", type: "wyr", cat: "powers", text: "Would you rather…", a: "never hit a red light again", b: "never wait more than 60 seconds for food again" },
  { id: "wyr-205", type: "wyr", cat: "deep", text: "Would you rather…", a: "be brilliant at giving advice but bad at taking it", b: "be great at taking advice but never asked for any" },
  { id: "wyr-206", type: "wyr", cat: "silly", text: "Would you rather…", a: "applause plays every time you finish a task", b: "a sad trombone plays every time you procrastinate" },
  { id: "wyr-207", type: "wyr", cat: "gross", text: "Would you rather…", a: "bite into an apple and find half a worm", b: "drink from a cup and feel something bump your lip (you never find out what)" },
  { id: "wyr-208", type: "wyr", cat: "spicy", text: "Would you rather…", a: "everyone hears your stomach's opinion of your meals", b: "everyone sees a live counter of your snoozed alarms" },
  { id: "wyr-209", type: "wyr", cat: "food", text: "Would you rather…", a: "perfect toast every time, but only one slice", b: "unlimited toast, always slightly wrong" },
  { id: "wyr-210", type: "wyr", cat: "money", text: "Would you rather…", a: "your savings account pays 20% but you can't touch it for 10 years", b: "normal interest but you can always access it" },
  { id: "wyr-211", type: "wyr", cat: "powers", text: "Would you rather…", a: "your hums harmonise with any song playing", b: "your claps are always perfectly on beat" },
  { id: "wyr-212", type: "wyr", cat: "deep", text: "Would you rather…", a: "know which of your habits will matter most in 20 years", b: "know which of your friendships will last forever" },
  { id: "wyr-213", type: "wyr", cat: "silly", text: "Would you rather…", a: "your socks always match but are never where you left them", b: "your socks never match but are always exactly where you look first" },
  { id: "wyr-214", type: "wyr", cat: "spicy", text: "Would you rather…", a: "your autocomplete suggestions are projected in meetings", b: "your hummed shower songs are your ringtone, updated weekly" },
  { id: "wyr-215", type: "wyr", cat: "food", text: "Would you rather…", a: "eat only foods that start with the same letter as your name for a month", b: "eat alphabetically through the supermarket for a month" },
  { id: "wyr-216", type: "wyr", cat: "money", text: "Would you rather…", a: "a free holiday every year, destination chosen by a stranger", b: "a half-price holiday every year, you choose" },
  { id: "wyr-217", type: "wyr", cat: "gross", text: "Would you rather…", a: "every handshake is 15% too moist", b: "every hug lasts 4 seconds too long" },
  { id: "wyr-218", type: "wyr", cat: "silly", text: "Would you rather…", a: "birds occasionally deliver you handwritten compliments", b: "squirrels occasionally leave you tiny useful tools" },
  { id: "wyr-219", type: "wyr", cat: "deep", text: "Would you rather…", a: "your average day gets 10% better forever", b: "your best days get twice as good but rarer" },
  { id: "wyr-220", type: "wyr", cat: "powers", text: "Would you rather…", a: "instantly dry off after any rain or swim", b: "never feel too hot or too cold again" },
  // ---- press the button: round two ----
  { id: "btn-111", type: "button", cat: "silly", text: "Every plant you own thrives magnificently…", catch: "but they visibly wilt, dramatically, whenever you leave the room." },
  { id: "btn-112", type: "button", cat: "money", text: "You get $1,000 every time you finish a book…", catch: "but you must write a 500-word review your friends can read." },
  { id: "btn-113", type: "button", cat: "deep", text: "You always make the right decision…", catch: "but you never learn anything from making them." },
  { id: "btn-114", type: "button", cat: "spicy", text: "You get a perfect memory for faces and names…", catch: "but you also remember exactly how every conversation ended." },
  { id: "btn-115", type: "button", cat: "food", text: "Your leftovers always taste better than the original meal…", catch: "but fresh food now always tastes like it needs one more day." },
  { id: "btn-116", type: "button", cat: "powers", text: "You can rewind any song to hear it for the first time again…", catch: "but each song only works once, ever." },
  { id: "btn-117", type: "button", cat: "silly", text: "Your bed makes itself…", catch: "but only if you say 'thank you, bed' out loud, in front of whoever is there." },
  { id: "btn-118", type: "button", cat: "money", text: "All parking is free for you forever…", catch: "but you must display a bumper sticker that says 'I PRESSED THE BUTTON'." },
  { id: "btn-119", type: "button", cat: "deep", text: "Everyone becomes immune to embarrassment…", catch: "including the people you rely on to be embarrassed into behaving." },
  { id: "btn-120", type: "button", cat: "spicy", text: "You know the exact moment someone starts liking you…", catch: "and the exact moment they stop." },
  { id: "btn-121", type: "button", cat: "food", text: "You get bottomless perfect nachos at any social event…", catch: "but the bowl loudly refills itself during quiet moments." },
  { id: "btn-122", type: "button", cat: "powers", text: "You never stub your toe again…", catch: "but every doorframe now audibly whispers 'careful' as you pass." },
  { id: "btn-123", type: "button", cat: "silly", text: "You can pet any animal safely, even wild ones…", catch: "but every animal you pet follows you for the rest of the day." },
  { id: "btn-124", type: "button", cat: "money", text: "Your phone never cracks, dies, or slows down…", catch: "but it takes one random unflattering selfie a week and sets it as your lock screen." },
  { id: "btn-125", type: "button", cat: "deep", text: "You gain one hour every day that no one else gets…", catch: "but you must spend it completely alone, no screens." },
];

// Sanity check: catch duplicate ids at load time (dev aid, silent in prod use).
(function () {
  const seen = new Set();
  for (const q of QUESTIONS) {
    if (seen.has(q.id)) console.error("DUPLICATE QUESTION ID: " + q.id);
    seen.add(q.id);
  }
})();
